version: '2'

services:
  web:
    build: .
    ports:
    - 8000:8000
    links:
    - database
    environment:
    - USER
  database:
    image: postgres
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
  selenium:
    # use standalone-chrome-debug if you want to VNC in and watch
    image: selenium/standalone-chrome
    ports:
    - 4444:4444
    - 5900:5900
    links:
    - web
    environment:
      SCREEN_WIDTH: 1500
      SCREEN_HEIGHT: 2000
